# Generated by Django 5.1.2 on 2024-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_coordinator_registered_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='profile_picture',
            field=models.ImageField(default='default-profile.jpg', upload_to='static/profile_pictures'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='profile_picture',
            field=models.ImageField(default='default-profile.jpg', upload_to='static/profile_pictures'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(default='default-profile.jpg', upload_to='static/profile_pictures'),
        ),
    ]
