# Generated by Django 5.1.2 on 2024-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_coordinator_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coord_prn', models.CharField(blank=True, max_length=20, null=True)),
                ('vol_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vol_prn', models.CharField(blank=True, max_length=20, null=True)),
                ('geo_photo', models.ImageField(blank=True, null=True, upload_to='geophotos/')),
                ('actual_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actual_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
