# Generated by Django 5.1.2 on 2024-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='activity',
            field=models.CharField(default='', max_length=30),
        ),
    ]
