# Generated by Django 4.2.16 on 2024-10-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_volunteer_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
