# Generated by Django 4.2.16 on 2024-10-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_attendance_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='role',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='role',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
    ]
