# Generated by Django 4.2.16 on 2024-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_coordinator_role_remove_secretary_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='qr_codeFE',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/Flagship/'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='qr_codeSS',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/Social_Services/'),
        ),
    ]
