# Generated by Django 4.2.16 on 2024-10-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_volunteer_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
