# Generated by Django 4.2.16 on 2024-10-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_attendance_geo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='geo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='geophotos/'),
        ),
    ]
