# Generated by Django 5.1.4 on 2025-01-07 04:14

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_auto_20241027_0356"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="roll",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="geo_photo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="activity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="flagshipEvent",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="failedregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="academic_year",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="activity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="domain",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="flagshipEvent",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="profile_picture",
            field=models.ImageField(
                default="default-profile.jpg",
                upload_to=authentication.models.profile_picture_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="activity",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="attendance",
            field=models.CharField(blank=True, default="", max_length=350),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="domain",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="email",
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="profile_picture",
            field=models.ImageField(
                default="default-profile.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
