# Generated by Django 5.1.4 on 2025-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_volunteer_roll_alter_activity_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="divisions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secretary",
            name="divisions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
