# Generated by Django 5.1.4 on 2025-01-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_activity_divisions_secretary_divisions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretary",
            name="divisions",
        ),
    ]
