# Generated by Django 5.1.2 on 2024-10-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
