# Generated by Django 5.1.2 on 2024-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='profile_picture',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
