# Generated by Django 4.2.16 on 2024-10-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_attendance_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='flagshipEvent',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
