# Generated by Django 5.1.2 on 2024-10-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_activity_time_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_IN_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
