# Generated by Django 4.2.16 on 2024-10-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_coordinator_qr_code_coordinator_qr_codefe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_year', models.CharField(default='2024-2025', max_length=10)),
                ('curr_sem', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='academic_year',
            field=models.CharField(default='FY', max_length=10),
        ),
    ]
