# Generated by Django 4.2.16 on 2024-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_delete_currentdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='domain',
            field=models.CharField(max_length=50),
        ),
    ]
