# Generated by Django 4.2.16 on 2024-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_activity_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
