# Generated by Django 4.2.16 on 2024-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_activity_venue_attendance_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='geo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='geophotos/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>'),
        ),
    ]
