"""
Django settings for SWD_Attendance project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7!_bb*67rwd-)&7=zbz%jxhb*ftci6adg$)lue4g7ms0ebf8+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'coordinator',
    'secretary',
    'volunteer',
    'action'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SWD_Attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SWD_Attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom settings
CURR_YEAR = '2024-2025'
CURR_SEM = 1
SECRETARY_YEAR = ['22', '23']
COORDINATOR_YEAR = ['22', '23']
VOLUNTEER_YEAR = ['24']

SECRETARY_KEY = 'Z4Q8L9'
COORDINATOR_KEY = 'F3N1X7'
VOLUNTEER_KEY = 'P5T2B6'

# Domain Allotment
DOMAIN_ALLOTMENT = {
    "CS-J": "Education, Awareness and Empowerment",
    "CS-K": "Education, Awareness and Empowerment",
    "CS-A": "Education, Awareness and Empowerment",
    "CS-B": "Education, Awareness and Empowerment",
    "CS-C": "Education, Awareness and Empowerment",
    "CS-D": "Education, Awareness and Empowerment",
    "CSSE-C": "Education, Awareness and Empowerment",
    "CSDS-A": "Education, Awareness and Empowerment",
    "CSDS-B": "Education, Awareness and Empowerment",
    "CS-L": "Education, Awareness and Empowerment",
    "IT-F": "Education, Awareness and Empowerment",
    "CSDS-C": "Health, well beign & awareness",
    "CS-I": "Health, well beign & awareness",
    "IT-E": "Health, well beign & awareness",
    "CSSE-A": "Health, well beign & awareness",
    "CSSE-B": "Health, well beign & awareness",
    "CS-E": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CS-F": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CS-G": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CS-H": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IC-A": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IC-B": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IC-C": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IT-A": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IT-B": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IT-C": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "IT-D": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CSCBI-A": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CSCBI-B": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CSCBI-C": "Enviormental Sustanablity ,Clieanliness and Awaraeness",
    "CSDS-A": "Community Development ,Social Support & Awareness",
    "CSDS-B": "Community Development ,Social Support & Awareness",
    
}

# Activity Domains
DOMAINS = {
    "Education, Awareness and Empowerment": ["Aashakiran", "Matadhikar", "Muskaan", "Udaan", "Utkarsh","Saksham"],
    "Health, well beign & awareness": ["Aavishkar", "Vatsalya", "Aadhar"],
    "Enviormental Sustanablity ,Clieanliness and Awaraeness":["Swaccha Pune","Go Green"],
    "Community Development ,Social Support & Awareness": ["Night Patrolling", "Animal Rescue","Lilliput"],
}

#Activity Status
ACTIVITIES = {
    "Aashakiran": False,
    "Matadhikar": True,
    "Muskaan": False,
    "Udaan": False,
    "Utkarsh": False,
    "Saksham": False,
    "Aavishkar":False,
    "Vatsalya":False,
    "Aadhar":False,
    "Swaccha Pune":False,
    "Go Green":False,
    "Night Patrolling":False,
    "Animal Rescur":False,
    "Lilliput":False,
}

FLAGSHIPS = ["Blood-D", "Utkarsh"]
