"""
Django settings for SWD_Attendance project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7!_bb*67rwd-)&7=zbz%jxhb*ftci6adg$)lue4g7ms0ebf8+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'coordinator',
    'secretary',
    'volunteer',
    'action'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SWD_Attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SWD_Attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom settings
CURR_YEAR = '2024-2025'
CURR_SEM = 1
SECRETARY_YEAR = ['22', '23']
COORDINATOR_YEAR = ['22', '23']
VOLUNTEER_YEAR = ['24']

SECRETARY_KEY = 'Z4Q8L9'
COORDINATOR_KEY = 'F3N1X7'
VOLUNTEER_KEY = 'P5T2B6'

# Domain Allotment
DOMAIN_ALLOTMENT = {
    "AIDS-A": "Education, Awareness and Empowerment",
    "AIDS-B": "Education, Awareness and Empowerment",
    "AIDS-C": "Education, Awareness and Empowerment",
    "AIDS-D": "Education, Awareness and Empowerment",
    "AIDS-E": "Education, Awareness and Empowerment",
    "AIDS-F": "Education, Awareness and Empowerment",
    "Civil-A": "Education, Awareness and Empowerment",
    "CE-A": "Education, Awareness and Empowerment",
    "CE-B": "Education, Awareness and Empowerment",
    "CE-C": "Education, Awareness and Empowerment",
    "CE-D": "Education, Awareness and Empowerment",
    "CE-E": "Education, Awareness and Empowerment",
    "CE-F": "Education, Awareness and Empowerment",
    "CE-G": "Education, Awareness and Empowerment",
    "CE-H": "Education, Awareness and Empowerment",
    "CE-I": "Health and Wellbeing",
    "CE-J": "Health and Wellbeing",
    "CE-K": "Health and Wellbeing",
    "CE-L": "Health and Wellbeing",
    "CE-SE-A": "Health and Wellbeing",
    "CE-SE-B": "Health and Wellbeing",
    "CE-SE-C": "Health and Wellbeing",
    "CSE-AIML-A": "Health and Wellbeing",
    "CSE-AIML-B": "Health and Wellbeing",
    "CSE-AIML-C": "Health and Wellbeing",
    "CSE-AIML-D": "Health and Wellbeing",
    "CSE-AIML-E": "Health and Wellbeing",
    "CSE-AIML-F": "Health and Wellbeing",
    "CSE-AI-A": "Health and Wellbeing",
    "CSE-AI-B": "Health and Wellbeing",
    "CSE-AI-C": "Community Development and Social Support",
    "CSE-AI-D": "Community Development and Social Support",
    "CSE-AI-E": "Community Development and Social Support",
    "CSE-AI-F": "Community Development and Social Support",
    "CSE-DS-A": "Community Development and Social Support",
    "CSE-DS-B": "Community Development and Social Support",
    "CSE-DS-C": "Community Development and Social Support",
    "CSE-ICS-A": "Community Development and Social Support",
    "CSE-ICS-B": "Community Development and Social Support",
    "CSE-ICS-C": "Community Development and Social Support",
    "ETC-A": "Community Development and Social Support",
    "ETC-B": "Community Development and Social Support",
    "ETC-C": "Community Development and Social Support",
    "ETC-D": "Community Development and Social Support",
    "ETC-E": "Community Development and Social Support",
    "ETC-F": "Environmental Sustainability and Cleanliness",
    "IT-A": "Environmental Sustainability and Cleanliness",
    "IT-B": "Environmental Sustainability and Cleanliness",
    "IT-C": "Environmental Sustainability and Cleanliness",
    "IT-D": "Environmental Sustainability and Cleanliness",
    "IT-E": "Environmental Sustainability and Cleanliness",
    "IT-F": "Environmental Sustainability and Cleanliness",
    "ICE-A": "Environmental Sustainability and Cleanliness",
    "ICE-B": "Environmental Sustainability and Cleanliness",
    "ICE-C": "Environmental Sustainability and Cleanliness",
    "ME-A": "Environmental Sustainability and Cleanliness",
    "ME-B": "Environmental Sustainability and Cleanliness",
    "ME-C": "Environmental Sustainability and Cleanliness",
    "ME-D": "Environmental Sustainability and Cleanliness",
    "ME-E": "Environmental Sustainability and Cleanliness",
    "ME-F": "Environmental Sustainability and Cleanliness"
}

# Activity Domains
DOMAINS = {
    "Education, Awareness and Empowerment": ["Aavishkar", "Matadhikar", "Muskaan", "Udaan", "Utkarsh"],
    "Health and Wellbeing": ["Blood-D", "Saarthi", "Saksham", "Vatsalya"],
    "Community Development and Social Support": ["Night Patrolling", "Animal Welfare"],
    "Environmental Sustainability and Cleanliness": ["Swaccha Pune", "Go Green"],
}

#Activity Status
ACTIVITIES = {
    "Aavishkar": False,
    "Matadhikar": True,
    "Muskaan": False,
    "Udaan": False,
    "Utkarsh": False,
    "Blood-D": True,
    "Saarthi": False,
    "Saksham": False,
    "Vatsalya": False,
    "Night Patrolling": False,
    "Animal Welfare": False,
    "Swaccha Pune": False,
    "Go Green": False
}

FLAGSHIPS = ["Blood-D", "Utkarsh"]
