"""
Django settings for SWD_Attendance project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7!_bb*67rwd-)&7=zbz%jxhb*ftci6adg$)lue4g7ms0ebf8+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    # 'admin_honeypot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'coordinator',
    'secretary',
    'volunteer',
    'action'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'SWD_Attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SWD_Attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = 'static'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = "/home/swdsmartattendancesystem/SWD_Attendance/media/"
# MEDIA_ROOT = 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom settings
CURR_YEAR = '2024-2025'
CURR_SEM = 1
SECRETARY_YEAR = ['22', '23']
COORDINATOR_YEAR = ['22', '23']
VOLUNTEER_YEAR = ['24']

SECRETARY_KEY = 'Z4Q8L9'
COORDINATOR_KEY = 'F3N1X7'
VOLUNTEER_KEY = 'P5T2B6'

# Domain Allotment
DOMAIN_ALLOTMENT = {
    "CS-J": "Education, Awareness and Empowerment",
    "CS-K": "Education, Awareness and Empowerment",
    "CS-A": "Education, Awareness and Empowerment",
    "CS-B": "Education, Awareness and Empowerment",
    "CS-C": "Education, Awareness and Empowerment",
    "CS-D": "Education, Awareness and Empowerment",
    "CSSE-C": "Education, Awareness and Empowerment",
    "CSDS-A": "Education, Awareness and Empowerment",
    "CSDS-B": "Education, Awareness and Empowerment",
    "CS-L": "Education, Awareness and Empowerment",
    "IT-F": "Education, Awareness and Empowerment",
    "CSDS-C": "Health, well being & awareness",
    "CS-I": "Health, well being & awareness",
    "IT-E": "Health, well being & awareness",
    "CSSE-A": "Health, well being & awareness",
    "CSSE-B": "Health, well being & awareness",
    "CS-E": "Environmental Sustainability, Cleanliness, and Awareness",
    "CS-F": "Environmental Sustainability, Cleanliness, and Awareness",
    "CS-G": "Environmental Sustainability, Cleanliness, and Awareness",
    "CS-H": "Environmental Sustainability, Cleanliness, and Awareness",
    "IC-A": "Environmental Sustainability, Cleanliness, and Awareness",
    "IC-B": "Environmental Sustainability, Cleanliness, and Awareness",
    "IC-C": "Environmental Sustainability, Cleanliness, and Awareness",
    "IT-A": "Environmental Sustainability, Cleanliness, and Awareness",
    "IT-B": "Environmental Sustainability, Cleanliness, and Awareness",
    "IT-C": "Environmental Sustainability, Cleanliness, and Awareness",
    "IT-D": "Environmental Sustainability, Cleanliness, and Awareness",
    "CSCBI-A": "Environmental Sustainability, Cleanliness, and Awareness",
    "CSCBI-B": "Environmental Sustainability, Cleanliness, and Awareness",
    "CSCBI-C": "Environmental Sustainability, Cleanliness, and Awareness",
}

# Activity Domains
DOMAINS = {
    "Education, Awareness and Empowerment": ["Aashakiran", "Matadhikar", "Muskaan", "Udaan", "Utkarsh","Saksham"],
    "Health, well being & awareness": ["Aavishkar", "Vatsalya", "Aadhar"],
    "Environmental Sustainability, Cleanliness, and Awareness":["Swaccha Pune","Go Green"],
    "Community Development, Social Support & Awareness": ["Night Patrolling", "Animal Rescue","Lilliput"],
}

#Activity Divisions
DIVISIONS = {
    "Utkarsh": ["CS-J", "CS-K"],
    "Matadhikar": ["CS-A", "CS-B", "CS-C", "CS-D"],
    "Muskaan": ["CSSE-C"],
    "Udaan": ["CSDS-A"],
    "Saksham": ["CSDS-B"],
    "Aashakiran": ["CS-L", "IT-F"],
    "Aavishkar": ["CSDS-C", "CS-I"],
    "Vatsalya": ["IT-E"],
    "Aadhar": ["CSSE-A", "CSSE-B"],
    "Swaccha Pune": ["CS-E", "CS-F", "CS-G", "CS-H", "IC-A", "IC-B", "IC-C"],
    "Go Green": ["IT-A", "IT-B", "IT-C", "IT-D", "CSCBI-A", "CSCBI-B", "CSCBI-C"],
    "Night Patrolling": ["CSDS-A"],
    "Lilliput": [],
    "Animal Rescue": [],
}

GROUPS = {
    "Utkarsh": ["1-15", "16-30", "31-45", "46-60", "61-78"],
    "Matadhikar": ["1-15", "16-30", "31-45", "46-60"],
    "Muskaan": [],
    "Udaan": ["1-23", "24-34", "35-46", "47-69"],
    "Saksham": [],
    "Aashakiran": [],
    "Aavishkar": ["1-26", "27-54", "55-78"],
    "Vatsalya": ["1-11", "12-22", "23-33", "34-44", "45-55", "56-66", "67-77"],
    "Aadhar": [],
    "Swaccha Pune": [],
    "Go Green": [],
    "Night Patrolling": [],
    # "Lilliput": [],
    # "Animal Rescue": [],
}

#Activity Status
ACTIVITIES = {
    "Aashakiran": True,
    "Matadhikar": True,
    "Muskaan": True,
    "Udaan": True,
    "Utkarsh": True,
    "Saksham": True,
    "Aavishkar":True,
    "Vatsalya":True,
    "Aadhar":True,
    "Swaccha Pune":True,
    "Go Green":True,
    "Night Patrolling":False,
    "Animal Rescue":False,
    "Lilliput":False,
}


FLAGSHIPS = ["Blood-D", "Utkarsh"]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'vitswd@vit.edu'
EMAIL_HOST_PASSWORD = 'wgvwtstogrdtihml'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# SESSION_EXPIRE_SECONDS = 600
# SESSION_TIMEOUT_REDIRECT = 'https://swdsmartattendancesystem.pythonanywhere.com/auth/'